version1
AlexKorot/MyLogApp pull request #1
Opened 2022-05-31 11:47 UTC by AlexKorot

2022-05-31 12:30 UTC, shadwork requested changes

2022-05-31 12:30 UTC, shadwork commented on .idea/gradle.xml
>  <?xml version="1.0" encoding="UTF-8"?>
add this file into gitignore and delete it from repo

2022-05-31 12:30 UTC, shadwork commented on .idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
add this file into gitignore and delete it from repo

2022-05-31 12:30 UTC, shadwork commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
add this file into gitignore and delete it from repo

2022-05-31 12:30 UTC, shadwork commented on app/src/main/res/values/strings.xml
> +    <string name="password_more_6">password can\'t be less than 6</string>
please check phrases in english, for example
password length can\'t be less than 6

2022-05-31 12:30 UTC, shadwork commented on app/src/main/res/values/colors.xml
> +    <color name="grey1">#8d8d8d</color>
Name should omitted numbers

2022-05-31 12:30 UTC, shadwork commented on app/src/main/res/layout/fragment_account.xml
> +    <androidx.cardview.widget.CardView
Customised cardview should be declared in theme

2022-05-31 12:30 UTC, shadwork commented on app/src/main/java/com/example/mylogapp/FragmentStart.kt
> +    // private lateinit var inAnimation : Animation
remove all comments from commit

2022-05-31 12:30 UTC, shadwork commented on app/src/main/java/com/example/mylogapp/FragmentStart.kt
> +        scaleAnimation.setAnimationListener(this)
setAnimationListener should be placed before startAnimation

2022-05-31 12:30 UTC, shadwork commented on app/src/main/java/com/example/mylogapp/FragmentLogin.kt
> +  //  fun isFieldEmpty(): Boolean{
all comments should be removed from repo

2022-05-31 12:30 UTC, shadwork commented on app/src/main/java/com/example/mylogapp/FragmentLogin.kt
> +        binding.loginButton.setOnClickListener {
read about ViewModel and rewrite this using ViewModel

2022-05-31 12:30 UTC, shadwork commented on app/src/main/java/com/example/mylogapp/FragmentLogin.kt
> +        if (binding.password.text.toString().trim().isEmpty()) {
Using 'when' statement

2022-06-01 08:14 UTC, AlexKorot commented on .idea/gradle.xml
>  <?xml version="1.0" encoding="UTF-8"?>
внесены изменения в gitignore

2022-06-01 08:15 UTC, AlexKorot commented on .idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
внесены изменения в gitignore

2022-06-01 08:15 UTC, AlexKorot commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
внесены изменения в gitignore

2022-06-01 08:17 UTC, AlexKorot commented on app/src/main/res/values/strings.xml
> +    <string name="password_more_6">password can\'t be less than 6</string>
проверены строки на английском(с помощью Гугл Транслате)

2022-06-01 08:17 UTC, AlexKorot commented on app/src/main/res/values/colors.xml
> +    <color name="grey1">#8d8d8d</color>
исправлено

2022-06-01 08:18 UTC, AlexKorot commented on app/src/main/java/com/example/mylogapp/FragmentStart.kt
> +    // private lateinit var inAnimation : Animation
исправлено , коментарии удалены

2022-06-01 08:19 UTC, AlexKorot commented on app/src/main/java/com/example/mylogapp/FragmentStart.kt
> +        scaleAnimation.setAnimationListener(this)
исправлено, слушатель перемешен

2022-06-01 08:19 UTC, AlexKorot commented on app/src/main/java/com/example/mylogapp/FragmentLogin.kt
> +  //  fun isFieldEmpty(): Boolean{
исправлено

2022-06-01 08:20 UTC, AlexKorot commented on app/src/main/java/com/example/mylogapp/FragmentLogin.kt
> +        binding.loginButton.setOnClickListener {
не реализовано, процесс продолжается, результатов нет, крашиться или работает криво.

2022-06-01 08:22 UTC, AlexKorot commented on app/src/main/java/com/example/mylogapp/FragmentLogin.kt
> +        if (binding.password.text.toString().trim().isEmpty()) {
не реализовано , в каждом if разные условия , каким образом использовать when решение не найдено

2022-06-01 15:15 UTC, shadwork commented on app/src/main/java/com/example/mylogapp/FragmentLogin.kt
> +        if (binding.password.text.toString().trim().isEmpty()) {
а как насчет неcкольких when ?

2022-06-01 15:15 UTC, shadwork commented on app/src/main/java/com/example/mylogapp/FragmentLogin.kt
> +        binding.loginButton.setOnClickListener {
а коделаб по вью модели пройден ? там тоже криво ?

2022-06-03 12:56 UTC, merged